### ISSUE TITLE
バフトリックの仕様変更

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#100]
現在のバフトリックの問題点に
・常にバフをかけていないといけないと焦らせて、結局攻撃に手が回らなくなる
・そもそもそんなにおいしい行動じゃない？
といった点があげられたので、
代替案にとして、
・ゲージが溜まりやすくなったり攻撃が上がる現行のバフトリック⇒を撃つたびに「次のトリックを強化されるバフ」を一つストックする仕様にしようと思います。
具体的に言うと、
一回バフトリックを撃つたびに「次のトリックが強化される」バフを一回分保持し、バフ以外のトリックが使われた場合、攻撃トリックであれば与えるダメージを増やし、回復トリックであれば回復量が増加するような効果を発揮して、ストックを消費します。一度にバフを保持できる数は6以上になります。

これを実装するにあたって発生する「ゲージの溜まりにくさの解消」は新しい仕様で補完します。
よろしくお願いします。

**Comment by lastre1208** [comment]
追記事項です。
溜まっているバフの数も可視化してほしいです。
限界以上のストックを溜めようとした場合は何も起こらないようにしてください。

**Comment by deigo6125** [comment]
少しわからないところがあったのですが、バフのストック数の可視化は制限時間のように数字で表したほうがいいですか？
または、トリックゲージなどのようにゲージのようなもので表現したほうがいいですか？

**Comment by lastre1208** [comment]
質問ありがとう！
まだ仮置きだからそんなに考えなくていいけど、とちらかと言えばゲージっぽくしてくれると見やすくて良いかな！
よろしくおねがいします！！

**Comment by deigo6125** [comment]
了解です！
