### ISSUE TITLE
波に乗り続ける時間に合わせてゲージの溜まり方が変化する仕様の実装

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#101]
バフトリックの仕様変更に伴い、新たに「長い間波に乗り続けているとゲージが溜まりやすくなる仕様」をつけます。
詳細を言うと、
・波に乗っている状態でチャージし続けていると徐々に溜まりやすくなっていく(上限アリ。2倍くらい？)
・ジャンプ後波に乗っていれば溜まりやすさはそのまま(チャージをしていれば)
・波から離れると溜まりやすさが元に戻っていく
・つまり常に溜まりやすい状態と溜まりにくい状態が移り変わる
・↑これらの溜まりやすさの趨勢は何かしらでプレイヤーに伝えられると〇(今なら光の強さなんかでもいい)
となります。
全く新しい仕様なので分からない点が多いと思うので質問どんどんお願いします。よろしくお願いします！
@deigo6125 @soltshio

**Comment by soltshio** [comment]
前に作ったゲージを溜めれば溜めるほど溜まりにくくなる仕様は消さずにそのままにしておいた方がいいですか？

**Comment by lastre1208** [comment]
コメントありがとう！
そこはそのままにしてほしいかな！
前の段々溜まりにくくなる仕様に対してのアプローチのバフが攻撃の妨げになってたから変えたわけだから、
溜まりにくくなる仕様自体は何も手つけなくても大丈夫です！
よろしくお願いします！！

**Comment by lastre1208** [comment]
間違えて一瞬タスク閉じちゃいました…
引き続き頑張ってください！

**Comment by soltshio** [comment]
了解です！

**Comment by soltshio** [comment]
波に乗り続けるほどトリックがたまりやすくなる仕様実装しました(マージするときにコンフリクトが起きちゃってエラーが無いようには直しましたがもしかしたらバグがあるかもしれないので確認お願いします)

**Comment by soltshio** [comment]
あとコードが汚いままなのでコードの整理は後程やります

**Comment by lastre1208** [comment]
確認しました！
これ今のところ
・設定された時間波に乗り続けられたら倍率が変化する
感じになってないかな？
説明不足で申し訳ないんだけど、
一定時間経ったら倍率が跳ね上がるんじゃなくて、
普通⇒溜まりやすい⇒凄い溜まりやすい⇒ちょっと溜まりやすい
みたいな、曲線的な変化が欲しいかな！
イメージ図貼っておくので参考にしてください！
よろしくお願いします！
[イラスト3](https://github.com/lastre1208/GameProduction_Team_B/assets/146053341/782f7456-6119-4425-8b9e-956122afbb6d)

**Comment by soltshio** [comment]
要望に合わせて修正しました。ChangeChargeTrickスクリプトから倍率が減る速度(増える時を1として)を変更できます(例えば減るときの速度と増える時の速度を同じにしたいときは1、減るときの速度を増える時の速度の2倍にしたい時は2に設定してください)。

**Comment by lastre1208** [comment]
確認しました！要望通りになってる！早めの修正助かります！！
エフェクトで溜まり具合が分かりやすくなってるのも良い！
タスク閉じときます！ありがとう！！！
