### ISSUE TITLE
ステージ生成の仕様変更に伴うスクリプト修正

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#109]

**Comment by soltshio** [comment]
どの方向に進んでも問題ないようにはなりましたがもしかしたら他にバグが潜んでるかもなので見つけたらお知らせください(進む方向を変更させてみたい時はGamePosオブジェクトの位置や方向の値をいじってください)

**Comment by lastre1208** [comment]
確認しました！GamePosの向いてる方向に子のオブジェクトが動く感じかな？
こっからランダム生成もできたら大分進むよ！！！！
難しいかもだけど桑原くんと2人でランダム生成チャレンジしてみるのもアリかもです(どっちかがリードするとかどっちかが書いてもう一人がご意見番するとか…やり方がお任せします)

まだいじりそうだからタスクはこのままにしとくね！！
早めの対応ありがとう！！！

**Comment by soltshio** [comment]
特に新しく作ったスクリプトは無くてほぼ前使ってたものの流用なのですが前からの変更点として

・MoveForward(前に進む)スクリプトをプレイヤーなどのオブジェクトから外してGamePosにつけて、GamePosの中に前に進ませたいものを入れることでプレイヤーなどが前に進むようにした。

・LimitMove(横の移動制限の)スクリプトを同じようにプレイヤーなどのオブジェクトから外してGamePosにつけて、移動制限させるオブジェクトにプレイヤーや敵を入れることで入れたオブジェクトを移動制限するようになった。

・敵の弾の生成関係のスクリプトを修正して敵の弾の向きが進行方向に向くようになりました(以前と使い方は変化なし)

・以上の変更によってGamePosが色んな方向に向かって動いても敵やプレイヤーの動き、敵の弾の動きや方向が影響なく動くようになった。

・MoveManagerは以上の変更により必要なくなったので削除した。

って感じです。
あとコードを少し整理した関係でChangeChargeTrickTheCharger(ゲージがたまるほど溜まりにくくなるスクリプト)を追加しましたが、以前のChargeTrickスクリプトから抜き出して今回作ったスクリプトに移し替えたので、トリックのたまり具合の調整はそのスクリプトから変更できます。
多分また今後の修正で色々変わるかもなのでその都度変更内容を伝えるようにします
