### ISSUE TITLE
トリックごとの効果分けの実装

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#36]
それぞれの効果は、
・攻撃(Bボタン)
・回復(Aボタン)
・バフ(攻撃力UPorゲージ回復量増加)(Xボタン)
となります。
ゲージは5~6分割(調整できるようにしてあると〇)で構成され、
一定量溜まるとトリック一回分が仕様できるようになる仕様です。
また、それぞれの効果の度合いを調整できるようなスクリプトの構造にしてください。

**Comment by soltshio** [comment]
そういえばトリックがたまっているほどダメージ量と移動スピードが上がるやつはまだ残しておいた方がいいですかね？(完全に要らないならその部分は消しておきます)

**Comment by lastre1208** [comment]
コメントありがとう！
今のところは無くてもいいかな！
ただ機能としてそれを無くすのは良いけどスクリプトからごっそり抜いちゃうと成果物としてのモノが無くなっちゃうからコメントアウトするぐらいで大丈夫です！！

**Comment by soltshio** [comment]
了解です！

**Comment by soltshio** [comment]
とりあえずトリックごとの効果分けの実装完了しました

**Comment by lastre1208** [comment]
実装ありがとう！後で確認させていただきます…！いつも仕事早くて助かるぜ
あとごめん言ってなかったから次からで良いんだけど、タスクの終了はタスクこなした人がやるより依頼者が見て問題無しってなったときに終了させたいから、今度はプルリクみたく〇〇したよ！の後俺とか誰かが見てokしてタスク閉じる形にしたい
引き続き残りのタスクお願いします！(無理はしないように！)

**Comment by soltshio** [comment]
了解です！
