### ISSUE TITLE
スコア機能の実装

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#42]
プレイヤーの取った行動からスコアを算出してください。
スコアになる元は
・ダメージを受けた回数(少ない程高スコア)
・クリアした際に残った時間(多い程高スコア)
・トリックを決めた回数(多い程高スコア←余裕があれば入れる)
・溜めたゲージ量(多い程高スコア←余裕があれば入れる)
となります。
まずは**評価の数値化を行うだけで大丈夫です。**
☆何個や、Sランク等の評価はレベルバランスの調整が済み次第検討します。
クリア画面に表示します。

**Comment by lastre1208** [comment]
#95 確認しました！！
ヘッダーもつけてて分かりやすくていいね！
評価項目の強さを自由に操作できるのもありがたい！！
デバッグ用に攻撃力すっげぇ高くなってるのは次プルリクするときに治してもらえれば大丈夫です！
タスク閉じときます！ありがとう！！

**Comment by deigo6125** [comment]
すみません、攻撃力の設定戻し忘れてました!
次回直しておきます！
iPhoneから送信

2024/06/20 16:24、lastre1208 ***@***.***>のメール:

﻿

#95<https://github.com/lastre1208/GameProduction_Team_B/pull/95> 確認しました！！
ヘッダーもつけてて分かりやすくていいね！
評価項目の強さを自由に操作できるのもありがたい！！
デバッグ用に攻撃力すっげぇ高くなってるのは次プルリクするときに治してもらえれば大丈夫です！
タスク閉じときます！ありがとう！！
