### ISSUE TITLE
攻撃時の振動の実装

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#47]
トリックボタンを押した瞬間にコントローラーの振動が起こるようにしてください。
ボタンを押して放す頃には振動が止まっているのがベストです。(3~5Fくらい？)←調節できるようにしてあると助かります。
振動の強さは連続してボタンが押される事が想定されるので弱めにしてください。

**Comment by soltshio** [comment]
ゲームクリアした時に振動し続けるバグがあったため応急処置としてEnemyスクリプトの死亡時の処理に無理やりバイブを止める(バイブ時間を0にする)処理を入れました
