### ISSUE TITLE
SURFの三面図の作成

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#67]
記載者：荒井　2024/06/12

**＜制作概要＞**
操作キャラクター「S.U.R.F」の三面図制作をお願いします。
基本的には以前書いていただいたデザインを基に制作してください。

三面図は以下の参考画像のように
・前面
・横面
・背面
の3面で構成してください。

**＜注意事項＞**
・画質は1920*1080等のHD画質で制作していただくのが良いかと思います。
　これより大きくしてもらう分には構いませんが(4K画質)、あまり差は無いかと思います。
・解像度は必ず350dpi以上で制作してください。MAYAに取り込んだ際に見えにくいなどの問題が発生しづらいかと思います。
・必ずTポーズで描いていただくようお願いします。

**＜仕様＞**
制作物...1点
・「S.U.R.F」三面図
・ファイル形式...「png(背景透過なし)」
・ファイル命名...「SURF_3shoot.png」

![Image](https://github.com/lastre1208/GameProduction_Team_B/assets/167687415/d1cb8ca1-c98c-4b12-8c09-2e24f62d7414)

**Comment by hatanakamaki** [comment]
三面図描きました！遅くなって申し訳ない！！

![Image](https://github.com/lastre1208/GameProduction_Team_B/assets/171664465/14e070e1-c6d3-4493-a89e-88dd444b9319)

**Comment by Arai0913** [comment]
お疲れ様です～！
少し直してほしい箇所があったので記載しました！
修正お願いします！

**今週末(日曜日 7/1)までにやっていただけると助かります...！**

![Image](https://github.com/lastre1208/GameProduction_Team_B/assets/167687415/851ffd52-0479-45a7-bf1c-7b17649b6ac6)

**Comment by hatanakamaki** [comment]
直しました！逆にでっぷりしちゃったかもしれない…

![Image](https://github.com/lastre1208/GameProduction_Team_B/assets/171664465/eda30472-2826-4b4b-8299-4e7e5e75ae86)

**Comment by Arai0913** [comment]
そこまででっぷりじゃないかと思います！
多分おしりの部分を少しだけシャープにしてやると印象変わるんじゃないかな...？と思います～
具体的な例探してるので後で追加しときます！

**Comment by hatanakamaki** [comment]
自分なりにおしりをちょっと削ってみました！
理想的なおしりじゃなかったらなんなりと指摘してください！！

![Image](https://github.com/lastre1208/GameProduction_Team_B/assets/171664465/fb5b369c-7900-42c9-819c-de19ec0dd66f)

**Comment by Arai0913** [comment]
良い感じだと思います！！
モデリングの際に少しまた調整も入ると思うので、現状で三面図は完了で良いかなと思います！
お疲れ様です！

データ等無くさないようにだけ気を付けて下さい！

**Comment by hatanakamaki** [comment]
ありがとうございます〜！！🙏🙏
