### ISSUE TITLE
トリックゲージの溜まり方の仕様の変更

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#80]
「最大までゲージを溜める事によるメリットと発生する課題」を作るため、コマンドを仮実装します。それに伴ってゲージの溜まり方に変更を加えます。
・各ゲージの溜まり方を一定でなくする
↑今までがトリック三回分のゲージを溜まるのに10+10+10で30だったのに対して、10+15+20と溜まるごとに一個分のゲージが溜まるのに必要なエネルギーの量が増加するようにしてください。(↑のはあくまで例です。)

**Comment by soltshio** [comment]
すみません質問です。例えばトリックゲージの最大値がそれぞれ10、20、30、40、50、60でそれぞれ10、20、30、40までたまっていて50のゲージが40までたまっていた時に、ゲージを一つ使ったら40のゲージが使われると思うのですが50のゲージが40までたまっていたので自動的に40のゲージが満タンになっちゃうと思うんですがそれでも大丈夫ですか？

**Comment by lastre1208** [comment]
コメントありがとう！すぐ返事できなくてごめん！
ゲージごとの貯まる量変えるとそういう弊害があるのか…
ゲーム的にはあまり望ましくない現象かな…ゲージの量＝何発撃てるかって目安だからゲージの分だけ撃てないとおかしいからね
申し訳ないけどそうならないようにしてほしいな…
今パッと思いついた対策としては、貯まる量はどのゲージも同じにして、後になればなるほど貯まるトリックゲージの量が減るみたいな方法で疑似的にゲージの最大値を増やせないかな？
1～6まで全部10だけど、貯まりやすさが1倍、0.9倍、0.8倍…みたいに減っていく感じ
こうすれば一回のトリックで使うゲージの数値は同じになってゲージ量とトリック使用回数の齟齬が無くなると思う
始めからこう発注かければよかったね…結構めんどくさいかもだけどまだ期限先なのでじっくりやってくれると助かります
お願いします！！

**Comment by soltshio** [comment]
了解です！とりあえずその方法でやってみます

**Comment by soltshio** [comment]
トリックゲージのたまり方の仕様の変更完了しました！

**Comment by lastre1208** [comment]
確認しました！
ちゃんと溜まりにくくなってるね！！
倍率をそれぞれ設定できるようになってるのも良きです！
今のところはバグ無いかな！
ありがとう！！！！
