### ISSUE TITLE
クロマクロデザイン推敲

### ISSUE THREAD

**Issue by Arai0913** [lastre1208/GameProduction_Team_B#86]
記載者：荒井　2024/06/14

**＜制作概要＞**
クロマクロのデザインの推敲です。
・遠めからでもマグロに見える
・体のパーツ分けをもっと大きく
この二点に気を付けてデザイン推敲をお願いします。

**＜注意事項＞**
・あくまで案出しなので画質はあまり気にしなくてよいです。HD画質あたりが丁度いいかなと思います。
　これより大きくしてもらう分には構いません(4Kなど)。

**＜仕様＞**
制作物...1点
・「クロマクロ」デザイン推敲案
・ファイル形式...「png(背景透過なし)」
・ファイル命名...「KUROMACRO_NewDesign_.png」

**Comment by hika1964** [comment]
![KUROMACRO_NewDesign_](https://github.com/lastre1208/GameProduction_Team_B/assets/171664622/cb0e74d2-6510-4345-b7bc-79e1e6a8e152)
こんな感じでどうでしょう...！
パイプ色悩んだので複数載せてます

**Comment by Arai0913** [comment]
良い感じですね！
個人的には3番目の色がしっくりきますね～
現状のパイプは少し太めなので、サイバーっぽい要素というものを加えるにあたって少し細くしてやったり、本数を増やしてみたりというのも手かと思います～
クロマクロ本体の見た目はかなり良いと思います！引き続きよろしくお願いします～

また、細かな箇所ですが口元の線を少し伸ばしてやると更にマグロっぽさが増すかと思います！
リアルのマグロは口もとに少しシワ？蛇腹？のようなものがあり、あると結構見た目の印象変わるかと！

![Image](https://github.com/lastre1208/GameProduction_Team_B/assets/167687415/72621999-50e3-4429-8e32-b2819add38a2)

![Image](https://github.com/lastre1208/GameProduction_Team_B/assets/167687415/268e7fce-f65a-46e2-b113-507e98e98e40)

**Comment by hika1964** [comment]
いくつか案考えてみました！確認お願いします~
![KUROMACRO_NewDesign_2](https://github.com/lastre1208/GameProduction_Team_B/assets/171664622/bb703317-9695-4a84-bb65-d7427ea45684)

**Comment by Arai0913** [comment]
結構変わりましたね〜！
体表赤くしたの良いと思います！ただ、遠くから見た時ちょっと赤味が強く見えるので、赤の明度少し下げてみて欲しいです！赤黒い色に持っていくというか...

サイバー要素の追加についてですが、上から一個目がシンプルで良いと思います！色味については実際モデルに起こしてからでも良いかな〜と思うので、おおまかなデザインは完成でいいと思います！

お疲れ様です〜！！
