### ISSUE TITLE
フィーバーゲージ(仮)の実装

### ISSUE THREAD

**Issue by lastre1208** [lastre1208/GameProduction_Team_B#93]
フィーバーゲージの仕様は、
トリックを行う事でゲージが溜まり、最大まで溜まる事でフィーバー状態に移行、自動で減少し、0になるまでフィーバー状態を継続します。

・ゲージの溜まり方は1回のジャンプで何回トリックが行われたかを参照して溜まります。
↑1回のジャンプで1回トリックを放つのを6回行うより、1回のジャンプで6回トリックを放つのを1回行う方が溜まりやすいようにしてください。←最大までゲージを溜めるメリットを作る為です。
・フィーバー状態は、攻撃の威力やトリックゲージの溜まりやすさが向上します。

**Comment by soltshio** [comment]
フィーバーゲージ実装しました(ただスクリプトが汚いので後程スクリプトの整理しておきます)
あとコロナですがいまのところ無症状なので、無理無い範囲でゲーム制作の作業をやっているのでご心配なく。
何かわからないこととかあれば遠慮なく質問どうぞ

**Comment by lastre1208** [comment]
確認しました！
ちゃんと要件満たしてて助かります！！
個人的に気になったのはフィーバーゲージちょっと溜まりにくすぎ？っていうのと、敵すっげぇ固くね？ってところかな！
これらはこっちでも直せるから後回しでも大丈夫です！
タスク閉じときます！ありがとう！！

コロナだけど、後から症状出るかもしれないから気をつけてね！！！
